apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
        - name: neo4j
          image: neo4j:latest
          env:
            - name: NEO4J_AUTH
              value: neo4j/$(NEO4J_PASSWORD)
          ports:
            - containerPort: 7474
            - containerPort: 7687
          volumeMounts:
            - name: neo4j-storage
              mountPath: /data
      volumes:
        - name: neo4j-storage
          persistentVolumeClaim:
            claimName: neo4j-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j-service
spec:
  selector:
    app: neo4j
  ports:
    - protocol: TCP
      port: 7474       # HTTP Port for Neo4j Browser
      targetPort: 7474
      nodePort: 30010  # Exposed Port on Host Machine
    - protocol: TCP
      port: 7687       # Bolt Port for Drivers
      targetPort: 7687
      nodePort: 30011  # Exposed Port on Host Machine
  type: NodePort

